### ISSUE TITLE
Cimpilifier

### ISSUE THREAD

**Issue by smythp** [negativa-ai/MMLB#5]
Is this not usable yet until Cimpilifier is available?

**Comment by jzh18** [comment]
> Is this not usable yet until Cimpilifier is available?

Hi, Cimplifier code will be available soon. Hopefully before the end of this week.

**Comment by smythp** [comment]
Cool, would like to try this out on some low-bloat images and see how they stack up. Could you update here when it's available?

**Comment by harshvp1621** [comment]
Any updates on the Cimplifier code?

**Comment by jzh18** [comment]
@smythp @harshvp1621 Hi, the Cimplifier code is added. Please check the latest readme about how to use it.

**Comment by smythp** [comment]
Great, in that case I'll close. If there are issues I'll reopen.
